### PR TITLE
Use local var for primary key field name

### PR DESCRIPTION
**Pull request by postmechanical**
Related to https://github.com/lonelyplanet/lpm-flagship-ios/issues/2286

### CODE REVIEW

**Comment by postmechanical** [comment]
@apanagar or @mmccroskey 👀 🙏

**Comment by mmccroskey** [comment]
@postmechanical Interesting -- why does this prevent the crash?

**Comment by postmechanical** [comment]
@mmccroskey It guards against an async modification to `g_primaryKeyFieldName` dictionary contents.

**Comment by mmccroskey** [comment]
@postmechanical 👍 Makes sense, and code looks good. :shipit:

**Pull request merged**
